### ISSUE TITLE
Zukünftige Perioden verschwinden

### ISSUE THREAD

**Issue by gecko17** [DHBW-Karlsruhe/businesshorizon2#215]
Wenn man von Schritt 3 auf Schritt 4 wechselt und dann wieder zu Schritt 3 zurück, verschwinden die Buttons für die Perioden, die in der Zukunft liegen.
Man kann also die Werte dort nicht mehr ändern.

**Comment by TobiasLindner** [comment]
Die Buttons gibt es im neuen UI nicht mehr
