### ISSUE TITLE
Fehlermeldung für Berechnungsfehler wird auf dem falschen Screen angezeigt

### ISSUE THREAD

**Issue by gecko17** [DHBW-Karlsruhe/businesshorizon2#216]
Wenn es einen Berechnungsfehler gibt (weil man z.B. überall die gleichen Werte eingibt), wird die Fehlermeldung auf dem Screen von Schritt 4 angezeigt, jedoch wird dem User schon der Screen von Schritt 5 mit der Ergebnisauswertung angezeigt. Das heißt der User sieht die Fehlermeldung garnicht. Erst wenn er einen Schritt zurück geht, sieht er den Fehler im Screen von Schritt 4.

**Comment by TobiasLindner** [comment]
Issue bezieht sich noch auf das alte UI. Im neuen UI neu und anders implementiert.
