### ISSUE TITLE
Fehlende Eingabeüberpüfung für Schritt 3 (Perioden)

### ISSUE THREAD

**Issue by gecko17** [DHBW-Karlsruhe/businesshorizon2#217]
Man kann beispielsweise alle Felder leer lassen und zum nächsten Schritt gehen. Erst am Ende kommt eine Fehlermeldung, dass es einen Berechnungsfehler gibt. Dieser Fehler sollte schon vorher abgefangen werden. Der User sollte gar nicht zum nächsten Schritt wechseln dürfen, wenn er z.B. alle Felder leer lässt, oder überall das gleiche eingibt.

**Comment by TobiasLindner** [comment]
Wird in zusammenhang mit der #247 bearbeitet

**Comment by TobiasLindner** [comment]
Thema wird in Issue #247 bearbeitet.
