### ISSUE TITLE
Fehlersymbol bei Schritt 2 geht nicht weg

### ISSUE THREAD

**Issue by gecko17** [DHBW-Karlsruhe/businesshorizon2#218]
In Schritt 2 gibt es ein Fehlersymbol (Ausrufezeichen neben dem fehlerhaften Feld), wenn man eine ungültige Eingabe macht.
Das funktioniert auch, aber folgendes Problem:
Wenn man den Fehler schon einmal hat und ändert dann die Werte auf:
Anzahl anzugebende, vergangener Perioden: 4
Anzahl einbezogener, vergangener Perioden: 3
Dann geht das Symbol für den Fehler nicht weg, obwohl jetzt der erste Wert größer 3 ist und größer als der zweite Wert (Das ist das Kriterium für einen Fehler). Es sollte also jetzt kein Fehler mehr kommen, aber es ist noch als fehlerhaft gekennzeichnet.

Gibt man direkt 4 und 3 an, dann kommt es nicht zu einem Fehler, nur wenn vorher ein Fehler da war.

**Comment by TobiasLindner** [comment]
Der Fehler kann so nicht mehr auftreten. Es wird nur noch ein Wert angegeben.
