### ISSUE TITLE
java.lang.NullPointerException bei Logout

### ISSUE THREAD

**Issue by JonathanLoewe** [DHBW-Karlsruhe/businesshorizon2#219]
Bei Logout direkt nach dem Anmelden kommt es zu einem Fehler:
![nullpointerexception_bei_logout](https://cloud.githubusercontent.com/assets/9131064/5373790/1e587896-805a-11e4-8931-8706e3ada31f.png)
Legt man zwischendurch beispielsweise ein Projekt an, kann man sich ganz normal abmelden.

**Comment by TobiasLindner** [comment]
Fehler tritt in neuem UI nicht mehr auf
Falls doch oder wenn ein ähnlicher Fehler auftritt einfach Issue wieder eröffnen
