### ISSUE TITLE
Ladekreis an komischen Positionen

### ISSUE THREAD

**Issue by gecko17** [DHBW-Karlsruhe/businesshorizon2#220]
Meistens hängt der Ladekreis irgendwo rechts oben rum, manchmal aber auch rechts mittig.
Er sollte immer in der Mitte sein, so dass der User ihn direkt erkennen kann. Ansonsten weiß er nicht, dass die Anwendung noch lädt und klickt mehrmals auf die Knöpfe.

Die Farbgebung ist fraglich. Was soll es Aussagen, dass der Ladekreis rot wird?

Man könnte auch die Anwendung blockieren, wenn sie lädt, damit der User so lange nichts drücken kann, bis sie fertig ist mit dem laden.

**Comment by TobiasLindner** [comment]
Ladekreis aktuell oben rechts im Eck
Evtl. gegen Ende fixen

**Comment by TobiasLindner** [comment]
Ladekreis zentriert.
Beim Ladenvorgang wird der Hintergrund ausgegraut.
