### ISSUE TITLE
Direktes Aufrufen der Projektergebnisse

### ISSUE THREAD

**Issue by felix2507** [DHBW-Karlsruhe/businesshorizon2#227]
Bei bestehenden Projekten ist es nicht möglich, die Ergebnisse direkt aufzurufen. Es müssen immer alle Screens durchgeblickt werden. 
Werte für die Berechnung sind vorhanden, da bereits vorbelegt bei den einzelnen Screens.

**Comment by TobiasLindner** [comment]
Für diese Funktion wäre eine Erweiterung des UI nötig. Meiner Meinung nach nicht mehr zu machen.
@SyChris111 kann man in die "To-Do"-Liste aufnehmen oder in eine Liste möglicher Erweiterungen
