### ISSUE TITLE
Passwörter werden im Klartext abgespeichert

### ISSUE THREAD

**Issue by felix2507** [DHBW-Karlsruhe/businesshorizon2#228]
Aktuell werden die Passwörter in Klartext in die Safe-File geschrieben. 
Müssen wir unbedingt umstellen!
Sollte zumindest mit einem einfachen Hash verschlüsselt werden.

**Comment by TobiasLindner** [comment]
Meiner Ansicht gab es keine Auffälligkeiten mehr oder @felix2507 ?

**Comment by TobiasLindner** [comment]
Meiner Meinung nach wurden keine Auffälligkeiten mehr festgestellt. Deshalb Issue geschlossen.
