### ISSUE TITLE
Berechnungsmethode im Projekt richtig setzen

### ISSUE THREAD

**Issue by gecko17** [DHBW-Karlsruhe/businesshorizon2#239]
In der Projekt-Klasse gibt es eine Liste für die Stochastischen und Deterministischen Methoden, da in der alten Version mehrere Berechnungsmethoden ausgewählt werden können. Nun wurde ja durch das EPK kommunziert, dass man nur eine Berechnungsmethode auswählen kann und die 3 zur Auswahl stehenden Methoden sind bei deterministischer und stochastischer Eingabe gleich. Das müsste in der Projektklasse nun geändert werden und entsprechende Setter und Getter Methoden zur Verfügung gestellt werden.
Erst dann kann ich damit im UI richtig arbeiten.
Habe mal Felix assigned, weil wir ja gesagt haben Felix und Johannes kümmern sich um solche Sachen, aber man kann nur eine Person assignen :dart:

**Comment by gecko17** [comment]
Das gleiche gilt für das Attribut ProjectInputType in der Projektklasse und darin dann das isStochastic und isDeterministic. Ein Projekt kann aktuell beides sein, soll aber nur eins möglich sein laut EPK und laut UI Mockups.

**Comment by TobiasLindner** [comment]
jop danke ;)
hab das jetzt schon so implementiert, dass es auf  auf die aktuell vorhanden isStochastic und isDeteministic zurückgreift. Wenn es jemand angepasst hat grad schreiben, dann pass ich das entprechend an

**Comment by felix2507** [comment]
ich habe es mir angeschaut und verstehe an dieser Stelle das Coding nicht so ganz. Wenn möglich würde ich das gerne am Mittwoch mit euch gemeinsam anschauen und abklären was genau zu tun ist.

**Comment by gecko17** [comment]
Gibt es schon eine Lösung?

**Comment by TobiasLindner** [comment]
vermulich ist an dieser Stelle nichts mehr zu tun?
Implementierung im Projektobjekt jetzt zu ändern macht keinen Sinn mehr.
@gecko17 @felix2507
