### ISSUE TITLE
Vereinheitlichen Eingabefelder

### ISSUE THREAD

**Issue by felix2507** [DHBW-Karlsruhe/businesshorizon2#245]
Die Eingabefelder für die Parameter arbeiten teilweise unterschiedlich.
Einige nutzen Kommas als Trennzeichen und andere Punkte. Diese sollten vereinheitlicht werden.

**Comment by TobiasLindner** [comment]
Inkonsistenzen bestehen nur zum Resultscreen. --> sehe ich als nicht kritisch...im Resultscreen das deutsche Format sinnvoll...Alle anderen Eingaben auf ","-Format umzustellen ist zu aufwändig.
Innerhalb des Resultsscreen wurden alle Werte um mindestens eine Nachkommastelle und maximal zwei ergänzt.
