### ISSUE TITLE
Obere Menüleiste anpassen (Top Bar Buttons)

### ISSUE THREAD

**Issue by felix2507** [DHBW-Karlsruhe/businesshorizon2#251]
Die Buttons in der oberen Menüleiste nach "Thema" sortieren.
Projekt Import/export nach rechts verschieben. 
Trennlinien zwischen den projektbezogenen Buttons und den Import/Export Buttons einfügen.

**Comment by gecko17** [comment]
Implementiert ohne die Trennlinie;
zu Viel Aufwand
